name:                mudblood
version:             0.1.0.0
license:             GPL-3
license-file:        LICENSE
author:              Philip Kranz
maintainer:          philip.kranz@googlemail.com
category:            Game
build-type:          Simple
cabal-version:       >=1.10

library
  exposed-modules:     Mudblood
                     , Mudblood.Class
                     , Mudblood.Component
                     , Mudblood.Core
                     , Mudblood.Monad
                     , Mudblood.Keys
                     , Mudblood.Error
                     , Mudblood.Encoding
                     , Mudblood.Text
                     , Mudblood.Screen
                     , Mudblood.Screen.Debug
                     , Mudblood.Screen.Simple
                     , Mudblood.Screen.Dummy
                     , Mudblood.Telnet
                     , Mudblood.Trigger
                     , Mudblood.Mapper
                     , Mudblood.UserData

                     , Mudblood.Trigger.Event
                     , Mudblood.Trigger.Regex
                     , Mudblood.Trigger.EventLog
                     , Mudblood.Trigger.Logfile

                     , Mudblood.Component.Logfile
                     , Mudblood.Component.Debug
                     , Mudblood.Component.Assets

                     , Data.GMCP
                     , Data.Error
                     , Data.Menu
                     , Data.Carte
                     , Data.DynEnv
                     , Data.Trie
                     , Data.QuasiEq
                     , Data.ListZipper

                     , Control.Component.Stateful
                     , Control.UnsafeCallback
                     , Control.Command
                     , Control.Trigger

                     , Unsafe.Any

  other-modules:       Mudblood.Mapper.Map
                     , Mudblood.Mapper.Json
                     , Mudblood.Mapper.Walk

                     , Text.Parsec.Word8

                       Control.Trigger.Core
                     , Control.Trigger.Iteration
                     , Control.Trigger.Parser
                     , Control.Trigger.Lift

  default-extensions:  MultiParamTypeClasses
                     , TypeOperators
                     , NoMonomorphismRestriction
                     , RankNTypes
                     , FlexibleContexts

  other-extensions:    GeneralizedNewtypeDeriving
                     , UndecidableInstances
                     , FlexibleInstances
                     , ScopedTypeVariables
                     , DeriveDataTypeable

  build-depends:       base
                     , parsec
                     , split
                     , mtl
                     , transformers
                     , containers
                     , utf8-string
                     , bytestring
                     , binary
                     , network
                     , aeson
                     , stm
                     , time
                     , MissingH
                     , bifunctors
                     , free
                     , fgl
                     , mmorph
                     , lens
                     , cereal
                     , data-default
                     , regex-tdfa
                     , base64-bytestring
                     , array
                     , ghc-prim
                     , filepath
                     , semigroups
                     , vector
                     , text
                     , directory
                     , text-ansi
                     , ansi-terminal

  hs-source-dirs:      src
  ghc-options:         -O1 -auto-all -caf-all
  default-language:    Haskell2010

executable mudblood-debug
  main-is: Debug.hs
  build-depends: base
               , mtl
               , containers
               , directory
               , gitrev
               , optparse-applicative
               , mudblood
               , lens
               , MissingH
  hs-source-dirs: app
  other-modules:
  default-language: Haskell2010
  ghc-options: -threaded

test-suite mudblood-trigger-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Trigger.hs
  build-depends:       base
                     , mtl
                     , transformers
                     , HUnit
                     , QuickCheck
                     , test-framework
                     , test-framework-hunit
                     , test-framework-quickcheck2
                     , mudblood
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  default-language:    Haskell2010
