name:                mudblood-core
version:             0.1.0.0
license:             GPL-3
license-file:        LICENSE
author:              Philip Kranz
maintainer:          philip.kranz@googlemail.com
category:            Game
build-type:          Simple
cabal-version:       >=1.10

library
  exposed-modules:     Mudblood
                     , Mudblood.Class
                     , Mudblood.Core
                     , Mudblood.Keys
                     , Mudblood.Error
                     , Mudblood.Text
                     , Mudblood.Screen.Simple
                     , Mudblood.Screen.Dummy
                     , Mudblood.Telnet
                     , Mudblood.Trigger
                     , Mudblood.Mapper
                     , Mudblood.UserData

                     , Data.GMCP
                     , Data.Menu
                     , Data.Carte
                     , Data.DynEnv
                     , Data.Trie
                     , Data.QuasiEq

                     , Control.DynCallback
                     , Control.UnsafeCallback
                     , Control.Trigger
                     , Control.Monad.Except

                     , Unsafe.Any

  other-modules:       Mudblood.Utils
                     , Mudblood.Mapper.Map
                     , Mudblood.Mapper.Walk

                     , Text.Parsec.Word8

                     , Control.Trigger.Core
                     , Control.Trigger.Forking
                     , Control.Trigger.Iteration
                     , Control.Trigger.Parser
                     , Control.Trigger.Lift

  default-extensions:  MultiParamTypeClasses
                     , TypeOperators
                     , NoMonomorphismRestriction
                     , RankNTypes

  other-extensions:    GeneralizedNewtypeDeriving
                     , UndecidableInstances
                     , FlexibleInstances
                     , FlexibleContexts
                     , ScopedTypeVariables
                     , DeriveDataTypeable

  build-depends:       base         == 4.7.*
                     , parsec       == 3.1.*
                     , split        == 0.2.*
                     , mtl          == 2.1.*
                     , transformers == 0.3.*
                     , containers   == 0.5.*
                     , utf8-string  == 1
                     , bytestring   == 0.10.*
                     , binary       == 0.7.*
                     , network      == 2.6.*
                     , json         == 0.9.*
                     , stm          == 2.4.*
                     , time         == 1.4.*
                     , MissingH     == 1.3.*
                     , bifunctors   == 4.2.*
                     , free         == 4.11.*
                     , fgl          == 5.5.*
                     , mmorph       == 1.0.*
                     , lens         == 4.7.*
                     , cereal       == 0.4.*
                     , data-default == 0.5.*

  hs-source-dirs:      src
  ghc-options:         -O1
  default-language:    Haskell2010

Test-Suite mudblood-core-tests
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  build-depends:       base                       == 4.7.*
                     , mudblood-core              == 0.1.*
                     , mtl                        == 2.1.*
                     , transformers               == 0.3.*
                     , Cabal                      == 0.22.*
                     , QuickCheck                 == 2.7.*
                     , HUnit                      == 1.2.*
                     , test-framework             == 0.8.*
                     , test-framework-quickcheck2 == 0.3.*
                     , test-framework-hunit       == 0.3.*
  main-is:             Trigger.hs
  ghc-options:         -O1
